### ISSUE TITLE
FAQ?

### ISSUE THREAD

**Issue by Nukecraft5419** [skygamezmc/SlashHub-Velocity#2]
Hi I usually use MyCommand on every server to get commands like /lobby, /hub, /bedwars and so on does it make sense to switch to your plugin just for the lobby command I use Velocity

**Comment by skygamezmc** [comment]
It depends. MyCommand is a great plugin for a lot of stuff, but one of the key differences is MyCommand runs strictly on the Spigot servers, whereas SlashHub runs on the proxy itself. SlashHub is made specifically for /hub and /lobby and offers a bit more control as to how many lobbys you have and how to randomly assort players between the different lobbys. SlashHub also offers more control over the messages and stuff. Switching to SlashHub for the /lobby commands and stuff would be more efficient as its run directly on the proxy and it would take up less space.

Personally, id say go for it, you wont be disappointed :))

**Comment by Nukecraft5419** [comment]
It would be great to improve the plugin like one that not only does that but also has the multi-lobby function usually there are no plug-ins that when you enter one of the lobbies you have entered

**Comment by skygamezmc** [comment]
Do you mind elaborating on that?

**Comment by Nukecraft5419** [comment]
Basically like when you entered a long time ago you used to use a plugin in bungeecord that allowed you to randomly enter one of the many lobbies only now it is no longer there and it would be handy to bring it to Velocity via your plugin as well

**Comment by skygamezmc** [comment]
im pretty sure we have that feature. in the config.toml file you can enter multiple lobbies into the list of server names and it should randomly send you to one or the other

**Comment by Nukecraft5419** [comment]
With your plugin you mean
